[package]
name = "bopus"
version = "0.1.0"
authors = ["Zen <true.grenight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
execute = "0.2.8"
regex = "1.4.3"
threadpool = "1.8.1"